### ISSUE TITLE
Pylibmc segment fault.

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/stonemason#1]
Pylibmc related segment fault when running tile server in threaded & processed mode (AWS ubuntu-14.04 HVM, not docker container image) :

```
python: libmemcached/io.cc:555: bool _io_write(memcached_server_write_instance_st, const void*, size_t, bool, size_t&): Assertion `ptr->fd != -1' failed.

*** Error in `/usr/bin/python': free(): invalid pointer: 0x0000000002e426e0 *** 
```

No problem when running locally on Mac.

**Comment by Kotaimen** [comment]
Problem caused by `Mason` is not inited in the flask worker thread, please implement lazy init like old `mason` tile server.
I have already switched `pylibmc` to `python-memcached`.

**Comment by GlieseRay** [comment]
Tile server has been refactored and mason object is lazy initialized by mason model now.
